@startuml
!theme crt-green
left to right direction

actor "User" as user

rectangle demo-java-swing {
  usecase "Copy Password" as copyPassword
  usecase "Generate Password" as generatePassword
}

user --> generatePassword
user --> copyPassword
@enduml