on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            **Release Notes: demo-java-swing Password Generator Application**

            We are excited to announce the initial release of the demo-java-swing Password Generator application! This user-friendly tool allows you to generate strong, secure passwords up to 16 characters, utilizing Java Swing for a seamless graphical interface. The application supports various character types, including uppercase letters, lowercase letters, digits, and special symbols, ensuring high-quality randomness and security. With an intuitive design, users can easily customize their password requirements, making it perfect for anyone looking to enhance their online security. Dive in and secure your digital presence with ease!
          draft: false
          prerelease: false